### ISSUE TITLE
Add README and LICENSE

### ISSUE THREAD

**Issue by shiena** [iuchim/zenhan#1]
sample for readme

----

# zenhan

Switch the mode of input method editor from terminal. This is a tool similar to [im-select](https://github.com/daipeihust/im-select).

see https://github.com/VSCodeVim/Vim#input-method

## Setting example

```json
"vim.autoSwitchInputMethod.enable": true,
"vim.autoSwitchInputMethod.defaultIM": "0",
"vim.autoSwitchInputMethod.obtainIMCmd": "D:\\bin\\zenhan.exe",
"vim.autoSwitchInputMethod.switchIMCmd": "D:\\bin\\zenhan.exe {im}"
```

**Comment by iuchim** [comment]
I added README & LICENSE file :)
Thanks!
